import { HateoasModel } from "../util/hateoas.util";

export class Postback extends HateoasModel{
  id: string;
  afid: string;
  prefix: string;
  date: string;
  time: string;
  clickid: string;
  offerid: string;
  sum: string;
  currency: string;
  goal: string;
  status: string;
  advname: string;
  offername: string;
  transactionid: string;
  idfa: string;
  gaid: string;
  t1: string;
  t2: string;
  t3: string;
  t4: string;
  t5: string;
  t6: string;
  t7: string;
  t8: string;
  t9: string;
  t10: string;
  secretkey: string;
  ipaddress: string;
  fullurl: string;
  postbacksend: string;
  duplicate: string;
  exchange: string;
  event1: string;
  event2: string;
  event3: string;
  event4: string;
  event5: string;
  event6: string;
  event7: string;
  event8: string;
  event9: string;
  event10: string;
  idc: string;
  ido: string;
}
